---
- include_tasks: versioncheck.yml
  when: submodules_versioncheck | bool

- name: Install unattended-upgrades
  apt:
    package: 'unattended-upgrades'
    state: present
  when: unattended_upgrades | bool


- name: Configure uau-mail to root
  template:
    src: 'template/52unattended-upgrades-local.j2'
    dest: '/etc/apt/apt.conf.d/52unattended-upgrades-local'
    owner: root
    group: root
    mode: 'u=rw,g=r,o=r'
  when: unattended_upgrades | bool
