---
- name: Install unattended-upgrades
  apt:
    package: 'unattended-upgrades'
    state: present
  when: unattended_upgrades


- name: Configure uau-mail to root
  template:
    src: 'files/52unattended-upgrades-local'
    dest: '/etc/apt/apt.conf.d/'
    owner: root
    group: root
    mode: 'u=rw,g=r,o=r'
  when: unattended_upgrades
