---
- include_tasks: versioncheck.yml
  when:
    - submodules_versioncheck | bool
    - ansible_os_family == 'Debian'

- name: Install unattended-upgrades
  become: true
  apt:
    package: 'unattended-upgrades'
    state: present
  when:
    - unattended_upgrades | bool
    - ansible_os_family == 'Debian'

- name: Configure uau-mail to root
  become: true
  template:
    src: 'template/52unattended-upgrades-local.j2'
    dest: '/etc/apt/apt.conf.d/52unattended-upgrades-local'
    owner: root
    group: root
    mode: 'u=rw,g=r,o=r'
  when: 
    - unattended_upgrades | bool
    - ansible_os_family == 'Debian'
